apiVersion: v1
kind: Service
metadata:
  labels:
    app: search-layer-cluster
  name: search-layer-cluster
  namespace: default
spec:
  ports:
  - name: search-layer-cluster
    port: 9088
    protocol: TCP
  selector:
    app: search-layer-cluster
